(*
 * $Id$
 * This file is part of the A2LView project.
 *
 * Copyright (c) 2009-2010 biegleux <biegleux[at]gmail[dot]com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, see <http://www.gnu.org/licenses>.
 *)
{ unit ids }
const
  uiGoldMine  = 66;
  uiStoneMine = 102;
  uiCliff1    = 264;
  uiCliff2    = 265;
  uiCliff3    = 266;
  uiCliff4    = 267;
  uiCliff5    = 268;
  uiCliff6    = 269;
  uiCliff7    = 270;
  uiCliff8    = 271;
  uiCliff9    = 272;
  uiCliff10   = 273;
  uiRelic     = 285;

  uiTurkey     = 833;
  uiSheep      = 594;
  uiMacaw      = 816;
  uiHawk       = 96;

  uiForageBush = 59;
  uiDeer       = 65;
  uiBoar       = 48;
  uiJavelina   = 822;

  uiFishShore   = 69;
  uiMarlin1     = 450;
  uiMarlin2     = 451;
  uiFishDorado  = 455;
  uiFishSalmon  = 456;
  uiFishTuna    = 457;
  uiFishSnapper = 458;

  CliffsAry: array[0..9] of Integer = (uiCliff1, uiCliff2, uiCliff3, uiCliff4, uiCliff5,
    uiCliff6, uiCliff7, uiCliff8, uiCliff9, uiCliff10);
